### ISSUE TITLE
Passing through Proxy to drakma:http-request

### ISSUE THREAD

**Issue by marto-tomato** [eudoxia0/trivial-download#6]
Hey I'm fairly new to lisp but I can't see how it is possible to pass keys like proxy through to the drakma:http-request

**Comment by eudoxia0** [comment]
Hmm, try the following:

```lisp
(let ((drakma:*default-http-proxy* (list "server.com" port-number)))
  (trivial-download:download ...))
```

**Comment by marto-tomato** [comment]
Yeh that works!
I didn't realise you could set the proxy that way.

Thanks
